export const genesisAudioMap: Record<number, any> = {
  1: require('../../assets/audio/genesis/1.mp3'),
  2: require('../../assets/audio/genesis/2.mp3'),
  3: require('../../assets/audio/genesis/3.mp3'),
  4: require('../../assets/audio/genesis/4.mp3'),
  5: require('../../assets/audio/genesis/5.mp3'),
  6: require('../../assets/audio/genesis/6.mp3'),
  7: require('../../assets/audio/genesis/7.mp3'),
  8: require('../../assets/audio/genesis/8.mp3'),
  9: require('../../assets/audio/genesis/9.mp3'),
  10: require('../../assets/audio/genesis/10.mp3'),
  11: require('../../assets/audio/genesis/11.mp3'),
  12: require('../../assets/audio/genesis/12.mp3'),
  13: require('../../assets/audio/genesis/13.mp3'),
  14: require('../../assets/audio/genesis/14.mp3'),
  15: require('../../assets/audio/genesis/15.mp3'),
  16: require('../../assets/audio/genesis/16.mp3'),
  17: require('../../assets/audio/genesis/17.mp3'),
  18: require('../../assets/audio/genesis/18.mp3'),
  19: require('../../assets/audio/genesis/19.mp3'),
  20: require('../../assets/audio/genesis/20.mp3'),
  21: require('../../assets/audio/genesis/21.mp3'),
  22: require('../../assets/audio/genesis/22.mp3'),
  23: require('../../assets/audio/genesis/23.mp3'),
  24: require('../../assets/audio/genesis/24.mp3'),
  25: require('../../assets/audio/genesis/25.mp3'),
  26: require('../../assets/audio/genesis/26.mp3'),
  27: require('../../assets/audio/genesis/27.mp3'),
  28: require('../../assets/audio/genesis/28.mp3'),
  29: require('../../assets/audio/genesis/29.mp3'),
  30: require('../../assets/audio/genesis/30.mp3'),
  31: require('../../assets/audio/genesis/31.mp3'),
  32: require('../../assets/audio/genesis/32.mp3'),
  33: require('../../assets/audio/genesis/33.mp3'),
  34: require('../../assets/audio/genesis/34.mp3'),
  35: require('../../assets/audio/genesis/35.mp3'),
  36: require('../../assets/audio/genesis/36.mp3'),
  37: require('../../assets/audio/genesis/37.mp3'),
  38: require('../../assets/audio/genesis/38.mp3'),
  39: require('../../assets/audio/genesis/39.mp3'),
  40: require('../../assets/audio/genesis/40.mp3'),
  41: require('../../assets/audio/genesis/41.mp3'),
  42: require('../../assets/audio/genesis/42.mp3'),
  43: require('../../assets/audio/genesis/43.mp3'),
  44: require('../../assets/audio/genesis/44.mp3'),
  45: require('../../assets/audio/genesis/45.mp3'),
  46: require('../../assets/audio/genesis/46.mp3'),
  47: require('../../assets/audio/genesis/47.mp3'),
  48: require('../../assets/audio/genesis/48.mp3'),
  49: require('../../assets/audio/genesis/49.mp3'),
  50: require('../../assets/audio/genesis/50.mp3'),
};

export const audioAssetsMap: Record<string, Record<number, any>> = {
  genesis: genesisAudioMap,
};
